### ISSUE TITLE
Cannot build a house on a bad foundations.

### ISSUE THREAD

**Issue by cohadar** [justradojko/CityDistances#4]
You have lots of problems in your code, and most of them are because you started without structure.
Your loadDataFromFile functions is loading data as Strings, but your data are not really strings.
Data is actually a pair of (Time, CityName). Make a new immutable data class, call it CityRecord and make cityList be a list of CityRecords, not list of strings.
See if this new organization of input data can give you some ideas what you are doing wrong. 

https://www.google.com/?q=immutable+object

**Comment by justradojko** [comment]
One of the biggest changes that I could see with introduction of Data class is that it simplified code a lot and made it more readable. Also it showed me that I was not understanding how some things are working in Java. 

Maybe there are some more points that would pop up if the app was more complex.

**Comment by cohadar** [comment]
The next point you need to realize is that object you want to put in HashMaps or HashSets as keys MUST have hashCode and equals defined properly.

Specifically CloseCities must have them defined.

Google: "java hashcode equals" and read on it until you understand what it is all about.
Than write hashCode and equals in such a way that trivially solves your duplication problem in CloseCities.
